name: Publish artifacts

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    name: Publish binary for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mfa-support-tool
            release_name: mfa-support-tool-linux-amd64-musl
            target: x86_64-unknown-linux-musl
            # strip: true
          - os: windows-latest
            artifact_name: mfa-support-tool.exe
            release_name: mfa-support-tool-windows-amd64.exe
            target: x86_64-pc-windows-msvc
            # strip: true
          - os: macos-latest
            artifact_name: mfa-support-tool
            release_name: mfa-support-tool-macos-amd64
            target: x86_64-apple-darwin
            # strip: true
          - os: macos-latest
            artifact_name: mfa-support-tool
            release_name: mfa-support-tool-macos-arm64
            target: aarch64-apple-darwin
            # strip: true

    steps:
      - uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      # - uses: svenstaro/upx-action@v2
      #   with:
      #     file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
      #     strip: ${{ matrix.strip }}
      #     args: ${{ matrix.args }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.release_name }}
          tag: ${{ github.ref }}